Don't use tty

diff --git a/latex/lcomp b/latex/lcomp
--- a/latex/lcomp
+++ b/latex/lcomp
@@ -1,13 +1,11 @@
 #!/usr/bin/env bash
-# Check if docker is installed
-if ! docker -v > /dev/null; then
-  echo "docker is not installed. Please install docker."
-  exit 1
-fi
 
 # Make sure that latex image is created
 DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && cd ../latex && pwd )"
 source $DIR/init.sh ""
+if [ $? != 0 ]; then
+  echo "Failed to create the latex image"
+fi
 
 # Go to the right directory (do it in the host not docker to allow access to ../file
 CUR_DIR=`pwd`
@@ -24,5 +22,5 @@ done
 
 # Run latexmk
 cd $LATEX_DIR
-docker run --rm -it -v "$PWD":/data -w /data latex /bin/sh -c "$LATEXMK_CMD"
+docker run --rm -i -v "$PWD":/data -w /data latex /bin/sh -c "$LATEXMK_CMD"
 cd $CUR_DIR
